name: Deploy on My Own Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧪 Set .env Variables
        run: |
          echo "NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}" > .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: 🛠️ Build Docker Image
        run: |
          docker build -t my-app-image .

      - name: 🧹 Remove Old Containers
        run: |
          for i in 1a 2a 3a 4a 5a; do
            docker rm -f instance$i || true
          done

      - name: 🚀 Start New Containers
        run: |
          for i in 1a 2a 3a 4a 5a; do
            docker run -d \
              --name instance$i \
              --env-file .env \
              --network coolify \
              my-app-image
          done
